### ISSUE TITLE
Assigning the value to input field

### ISSUE THREAD

**Issue by kaarleenzz** [vladmalik/pasteimage#3]
How would the:"Then assign sourceString to an input field and submit with form (or use ajax)." exactly work?

I'm trying like:
$("#img").val(sourceString); 

that doesn't work.

**Comment by vladmalik** [comment]
If you want to assign it to an image to display on the page, see sample.html provided. sourceString is the URI of the image, which you'll want to assign $("#img").attr("src", sourceString); 

On the other hand if you want to upload the image, then #img has to be a text <input> element and $("#img").val(sourceString) is right. All you need then is to submit that input field with a form or using ajax. The front-end part is done.

On the back end, if you're using PHP, you'll want to take the $_POST value, strip the "...base64," prefix, convert the base64-encoded string to an image, and then write that image to a file. All the code is provided in the readme file (see option 2).

**Comment by vladmalik** [comment]
I elaborated the readme file Option 2.
